server:
  port: 9191

spring:
  kafka:
    producer:
      bootstrap-servers: PLAINTEXT://172.21.216.5:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: PLAINTEXT://172.21.216.5:9092
      group-id: jt-group
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer